### ISSUE TITLE
Broke my code

### ISSUE THREAD

**Issue by femb-y** [saintdaddy/Vare-Obfuscator#3]
Failed to execute script 'CuldR6Unlocker_V1.py' due to unhandled exception: No module named 'sqlite3'

Traceback (most recent call last):
  File "CuldR6Unlocker_V1.py", line 2, in <module>
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'sqlite3'

Broke my code, any way to fix this?

**Comment by theabysslol** [comment]
pip install sqlite3

**Comment by saintdaddy** [comment]
if he converted the code to exe without specifying the modules, this error is normal, i have already explained this. Also available version [2.0](https://github.com/saintdaddy/Vare-Obfuscator2.0) is much better
